# Comparing against Volume Prediction Models
To get an idea of potential accuracy of my estimates, I will compare them against current volume prediction models for those sub-catchments

## Data organizing/building
```{r, eval = TRUE, echo = F}
gsdvol= readxl::read_excel('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\processed_summary_data\\Catchment_Stats.xlsx', sheet = 'Vol_Summaries', na = ' ')
library(ggplot2)
head(gsdvol)
```
```{r, eval = TRUE, echo = F}
est_vol = gsdvol[c(1,2)]
wall_vol = gsdvol[,c(1,3)]
g14 = gsdvol[,c(1,4)]
est = 'imagery'
wall = 'Wall (2022)'
gart = 'Gartner (2014) 1yr'

wall_vol = cbind(wall_vol, wall)
colnames(wall_vol) = c('Site','VolM', 'Source')
g14 = cbind(g14, gart)
colnames(g14) = c('Site','VolM', 'Source')
est_vol = cbind(est_vol, est)
colnames(est_vol)= c('Site', 'VolM', 'Source')

all = rbind(g14, wall_vol)
all = cbind(all, est_vol[2])
colnames(all) = c('Site', 'VolM', 'Source', 'EstVol')
gartnervol = cbind(g14, est_vol[2])
wall_vol = cbind(wall_vol, est_vol[2])
colnames(wall_vol) = c('Site', 'VolM', 'Source', 'EstVol')
colnames(gartnervol) = c('Site', 'VolM', 'Source', 'EstVol')
```

## Get Standard Deviations
recurrence interval
```{r, eval = TRUE, echo = TRUE}
risd = gartnervol[,-c(3)]
risd$diff = NA
rows = c(1:31)
for (i in rows){
  risd[i,4] = (risd[i,2]-risd[i,3])
}
g14_out = boxplot.stats(risd$diff, coef = 1)$out
g14_outind = which(risd$diff %in% c(g14_out))
risddev = sd(na.omit(risd$diff))
```

wall standard deviation
```{r, eval = TRUE, echo = TRUE}
wallsd = wall_vol[,-c(3)]
wallsd$diff= NA
rows = c(1:31)
for (i in rows){
  wallsd[i,4] = (wallsd[i,2]-wallsd[i,3])
}
```
remove outlier
```{r, eval = TRUE, echo = TRUE}
wall_out = boxplot.stats(wallsd$diff)$out
wall_outind = which(wallsd$diff %in% c(wall_out))
walldev = sd(na.omit(wallsd$diff)) 
```
standard deviation, all plots
```{r, eval = TRUE, echo = TRUE}
allsd = all[,-c(3)]
allsd$diff = NA
rows = c(1:62)
for (i in rows){
  allsd[i,4]= (allsd[i,2]- allsd[i,3])
}
```
remove outlier
```{r, eval = TRUE, echo = TRUE}
out = boxplot.stats(allsd$diff)$out
out_ind = which(allsd$diff %in% c(out))
all_nout = allsd[-c(out_ind),]
```
```{r, eval = TRUE, echo = TRUE}
alldev = sd(na.omit(all_nout$diff))
```

## Plots

```{r, eval = TRUE, echo = FALSE}
wallvolplot = ggplot(data = na.omit(wall_vol)) + geom_point(data = wall_vol, aes(EstVol, VolM, color = Source)) + scale_color_manual(values = c('Wall'= 'cornflowerblue')) +geom_abline(mapping = NULL, data = NULL, 1, 0) +xlim(0,25000) + ylim(0,25000) +ylab('Modeled Initial Volume (m3)') + xlab('Estimated Initial Volume from Imagery (m3)') + ggtitle('Wall (2022) Volume Model')+ theme_bw() + theme(legend.position = 'none')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = walldev, linetype = 'dashed')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = -walldev, linetype = 'dashed')+ expand_limits(x=0,y=0)
wallvolplot
```

```{r, eval = TRUE, echo = FALSE}
allplot = ggplot(data = na.omit(all), aes(EstVol, VolM, shape= Source)) + geom_point() +scale_color_manual(values = c('black','black')) + scale_shape_manual(values = c(1, 16)) + geom_abline(mapping = NULL, data = NULL, 1, 0) + ylim(0,32000) +ylab('Modeled Initial Volume (m3)') + xlab('Estimated Initial Volume from Imagery (m3)')  + theme_bw()+ labs(color ='Volume Model')+ expand_limits(x=0,y=0) + theme(legend.position = 'none')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = -alldev, linetype = 'dashed') + geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = alldev, linetype = 'dashed')
allplot
```

```{r, eval = TRUE, echo = FALSE}
lnvolwall = gsdvol[,c(1,5)]
lnvolwall$Source = 'Wall'
lnvolg14 = gsdvol[,c(1,6)]
lnvolg14$Source = 'Gartner 14'
lnvolimg = gsdvol[,c(1,7)]
lnvolimg$Source = 'Imagery'
lnvolwall = cbind(lnvolwall, lnvolimg[2])
lnvolg14 = cbind(lnvolg14, lnvolimg[2])
colnames(lnvolwall) = c('Site', 'ln_vol', 'Source', 'LnEstInt')
colnames(lnvolg14) = c('Site', 'ln_vol', 'Source', 'LnEstInt')
colnames(lnvolimg) = c('Site', 'ln_vol', 'Source', 'LnEstInt')
```

```{r, eval = TRUE, echo = FALSE}
lnvol = rbind(lnvolwall,lnvolg14)
```
```{r, eval = TRUE, echo = FALSE}
lnvolplot = ggplot(data = lnvol, aes(LnEstInt,ln_vol, color = Source)) + geom_point() +  geom_abline(mapping = NULL, data = NULL, 1, 0) +ylab('ln(Modeled Volume) (m3)') + xlab('ln(Estimated Initial Volume from Imagery) (m3)') + ggtitle('ln(Vol)') + theme_bw() +ylim(0,11) + xlim(0,11)
lnvolplot
```



