# Grain Size Distribution Plots

For now, this is just documentation of modeled grain sizes for the debris flow fans. I imagine eventually I will use these to compare between sites. 

```{r, echo = F, eval = T}
gsd = read.csv('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\processed_summary_data\\DF_gsd.csv', header = T, na.strings = '')
head(gsd)
```
```{r, echo = F, eval = T}
library(ggplot2)
d16phi = gsd[,c(1, 3:5)]
d50phi = gsd[,c(1, 6)]
colnames(d50phi) = c('DF_ID', 'size')
d50phi$perc = 'd50'
d84phi = gsd[, c(1, 7)]
colnames(d84phi) = c('DF_ID', 'size')
d84phi$perc = 'd84'
library(tidyverse)
library(magrittr)
d16phi_t = d16phi %>% pivot_longer(cols = 2:4, names_to = 'yr', values_to = 'size')
d16phi_t$perc = 'd16'
d16phi_t = d16phi_t[,-c(2)]

all = rbind(d16phi_t, d50phi, d84phi)
all = mutate(all, mm = 10**(-1*size)/3.322)
```

```{r, echo = F, eval = T}
gsdplot = ggplot(data = na.omit(all), aes(size, fill =  perc, after_stat(count))) + geom_density( alpha = .3) + scale_x_reverse() + xlab('phi') + labs(fill = 'Percent Finer Than')+ylab('Count')
gsdplot
```
