# Some possible correlated variables

These are some very preliminary scatter plots for potential predictor and response variables. I still have data to gather :). 
```{r, eval = T, echo = F}
library(ggplot2)
library(tidyverse)
df_morph = read.csv('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\processed_summary_data\\df_morphology.csv', header = T, na.strings = '')
```
Confinement Plot
```{r, eval = T, echo = F}
confinement = df_morph[, c(2,9, 19)]
colnames(confinement) = c('Site', 'inst_r_perc', 'confinement')
confinementplot = ggplot(data = na.omit(confinement), aes(confinement, inst_r_perc)) + geom_point() + ylab('Percent Instantly Removed') + xlab(' ')
confinementplot
```
Accomodation Space
```{r, eval = T, echo = F}
acc_space = df_morph[,c(2, 9, 22)]
acc_space = cbind(acc_space, confinement[3])
colnames(acc_space) = c('Site', 'inst_r_perc', 'acc_space', 'confinement')
accplot = ggplot(data = na.omit(acc_space), aes(acc_space, inst_r_perc, color = confinement)) + geom_point()+ ylab('Percent Instantly Removed')
accplot
```
Runout Percent of Valley Bottom
```{r, eval = T, echo = F}
runout = df_morph[,c(2,9, 21)]
runout = cbind(runout, confinement[3])
colnames(runout) = c('Site', 'inst_r_perc', 'runout_perc','confinement')
runout$runout_perc[runout$runout_perc > 100] = 100
runoutplot = ggplot(data = na.omit(runout), aes(runout_perc, inst_r_perc, color = confinement)) + geom_point() +ylab('Percent Instantly Removed')
runoutplot
```
Angle Plot
```{r, echo = F, eval = T}
RF_angle = df_morph[,c(2,9,6)]
RF_angle = cbind(RF_angle, confinement[3])
angleplot = ggplot(data = na.omit(RF_angle), aes(RF_angle, inst_r_perc, color = confinement)) + geom_point()+ylab('Percent Instantly Removed')
angleplot
```
Sinuosity Pre-fire
```{r, eval = T, echo = F}
sinuosity_pre = df_morph[,c(2,9,13)]
sinuosity_pre = cbind(sinuosity_pre, confinement[3])
sinuosity_preplot = ggplot(data = na.omit(sinuosity_pre), aes(sin_pre, inst_r_perc, color = confinement)) + geom_point()+ylab('Percent Instantly Removed')
sinuosity_preplot
```
Sinuosity Post-fire
```{r, eval = T, echo = F}
sinuosity_post = df_morph[,c(2,9,14)]
sinuosity_post = cbind(sinuosity_post, confinement[3])
sinuosity_postplot = ggplot(data = na.omit(sinuosity_post), aes(sin_post, inst_r_perc, color = confinement)) + geom_point() + ylab('Percent Instantly Removed')
sinuosity_postplot
```
Days above Bankfull
```{r, eval = T, echo = F}
dabf = df_morph[,c(2,9,24)]
dabf = cbind(dabf, confinement[3])
dabfplot = ggplot(data = na.omit(dabf), aes(dabf_postdep, inst_r_perc, color = confinement)) + geom_point() + ylab('Percent Instantly Removed')
dabfplot
```
