
```{r}
gross_sum_tdf = read.csv('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\processed_summary_data\\Gross_Summary_Vol_tdf.csv', header = T, na.strings = ' ')
head(gross_sum_tdf)
```

```{r}
colnames(gross_sum_tdf) = c('Site','EstInt', '0', '1','2','3','4','5','6','7','8','9','10')
gross_sum_t_perc = gross_sum_tdf
```

```{r}
gross_sum_t_perc[,2] = 100
```

```{r}
l1 = list(3,4,5,6,7,8,9,10,11,12,13)
for (i in l1){
  gross_sum_t_perc[,i] = round((gross_sum_tdf[,i]/gross_sum_tdf[,2]*100),1)
}
```

```{r}
gross_sum_t_perc = gross_sum_t_perc[-c(13:17),]
```

```{r}
brian_head = gross_sum_t_perc[(1:2),]
dollar_ridge = gross_sum_t_perc[(3:6),]
twitchell = gross_sum_t_perc[(7:14),]
pole_creek = gross_sum_t_perc[(15:17),]
seeley= gross_sum_t_perc[(18:19),]
shingle= gross_sum_t_perc[(20:21),]
trail_mountain = gross_sum_t_perc[(22:23),]
clay_springs = gross_sum_t_perc[24:26,]
```

```{r}
write.csv(brian_head, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Brian_Head\\volume.csv', row.names = TRUE)
write.csv(dollar_ridge, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Dollar_Ridge\\volume.csv', row.names = TRUE)
write.csv(twitchell, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Twitchell\\volume.csv', row.names = TRUE)
write.csv(pole_creek, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Pole_Creek\\volume.csv', row.names = TRUE)
write.csv(seeley, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Seeley\\volume.csv', row.names = TRUE)
write.csv(shingle, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Shingle\\volume.csv', row.names = TRUE)
write.csv(trail_mountain, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Trail_Mountain\\volume.csv', row.names = TRUE)
write.csv(clay_springs, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Clay_Springs\\volume.csv', row.names = TRUE)
```
```{r}
#subsetting sites with multiple debris flows
twitchell_FC4 = gross_sum_tdf[16,]
twitchell_FC5_1 = gross_sum_tdf[13,]
twitchell_FC5_2 = gross_sum_tdf[14,]
twitchell_FC7 = gross_sum_tdf[15,]
twitchell_SC2 = gross_sum_tdf[17,]
```

```{r}
perc_FC4_1 = twitchell_FC4
perc_FC4_1[,2] = 100
perc_FC5_1 = twitchell_FC5_1
perc_FC5_1[,2] = 100
perc_FC5_2 = twitchell_FC5_2
perc_FC5_2[,2] = 100
perc_FC7 = twitchell_FC7
perc_FC7[,2] = 100
perc_SC2 = twitchell_SC2
perc_SC2[,2] = 100
```

```{r}
for (i in l1) {
  perc_FC4_1[,i] = round((twitchell_FC4[,i]/twitchell_FC4[,2]*100),1)
  perc_FC5_1[,i] = round((twitchell_FC5_1[,i]/twitchell_FC5_1[,2]*100),1)
  perc_FC5_2[,i] = round((twitchell_FC5_2[,i]/twitchell_FC5_2[,2]*100),1)
  perc_FC7[,i] = round((twitchell_FC7[,i]/twitchell_FC7[,2]*100),1)
  perc_SC2[,i] = round((twitchell_SC2[,i]/twitchell_SC2[,2]*100),1)
}
```

```{r}
library(magrittr)
library(tidyr)
library(ggplot2)
brian_head_t = brian_head %>% pivot_longer(cols = EstInt:'10' , names_to = 'Time', values_to = 'Volume')
dollar_ridge_t = dollar_ridge %>%pivot_longer(cols = EstInt:'10' , names_to = 'Time', values_to = 'Volume')
twitchell_t = twitchell %>% pivot_longer(cols = EstInt:'10', names_to = 'Time', values_to = 'Volume')
pole_creek_t = pole_creek %>% pivot_longer(cols = EstInt:'10' , names_to = 'Time', values_to = 'Volume')
seeley_t = seeley %>% pivot_longer(cols = EstInt:'10' , names_to = 'Time', values_to = 'Volume')
shingle_t = shingle %>% pivot_longer(cols = EstInt:'10' , names_to = 'Time', values_to = 'Volume')
clay_springs_t = clay_springs %>% pivot_longer(cols =  EstInt:'10' , names_to = 'Time', values_to = 'Volume')
trail_mountain_t = trail_mountain %>% pivot_longer(cols =  EstInt:'10' , names_to = 'Time', values_to = 'Volume')
gross_sum_t_perc_t = gross_sum_t_perc %>% pivot_longer(cols =  EstInt:'10' , names_to = 'Time', values_to = 'Volume')
gross_sum_t_perc_t$Fire = NA
perc_FC4_t = perc_FC4_1 %>%pivot_longer(cols =  EstInt:'10' , names_to = 'Time', values_to = 'Volume')
perc_FC5_1_t = perc_FC5_1 %>% pivot_longer(cols =  EstInt:'10' , names_to = 'Time', values_to = 'Volume')
perc_FC5_2_t = perc_FC5_2 %>% pivot_longer(cols =  EstInt:'10' , names_to = 'Time', values_to = 'Volume')
perc_FC7_t = perc_FC7 %>% pivot_longer(cols =  EstInt:'10' , names_to = 'Time', values_to = 'Volume')
perc_SC2_t = perc_SC2 %>% pivot_longer(cols =  EstInt:'10' , names_to = 'Time', values_to = 'Volume')
```
```{r}
gross_sum_t_perc_t[c(1:24),4] = 'Brian Head'
gross_sum_t_perc_t[c(25:72),4] = 'Dollar Ridge'
gross_sum_t_perc_t[c(73:168),4]= 'Twitchell'
gross_sum_t_perc_t[c(169:204),4] = 'Pole Creek'
gross_sum_t_perc_t[c(205:228),4] = 'Seeley'
gross_sum_t_perc_t[c(229:252), 4] = 'Shingle'
gross_sum_t_perc_t[c(253:276),4] = 'Trail Mountain'
gross_sum_t_perc_t[c(277:323), 4] = 'Clay Springs'
perc_FC4_t$Fire = 'Twitchell'
perc_FC5_1_t$Fire = 'Twitchell'
perc_FC5_2_t$Fire = 'Twitchell'
perc_FC7_t$Fire = 'Twitchell'
perc_SC2_t$Fire = 'Twitchell'
```

```{r}
gross_vol_all = ggplot(data = na.omit(gross_sum_t_perc_t), aes(Time, Volume, color = Fire, group = Site)) + geom_point() + geom_line() + ggtitle('Estimated Percent Volume over Time') + xlab('Time Since Debris Flow (Years)') + ylab('Percent Remaining Volume') + ylim(0,100) + scale_x_discrete(limit = c('EstInt','0', '1','2','3','4','5','6','7','8','9','10')) + theme_bw() + geom_line(data= na.omit(perc_FC5_1_t)) + geom_line(data= na.omit(perc_FC5_2_t)) + geom_line(data= na.omit(perc_FC7_t)) + geom_line(data = na.omit(perc_SC2_t)) +geom_line(data = na.omit(perc_FC4_t)) +ggtitle('Debris Flow Fan Estimated Volume over Time')+ geom_point(data = na.omit(perc_FC5_1_t)) + geom_point(data= na.omit(perc_FC5_2_t))  + geom_point(data= na.omit(perc_FC7_t)) + geom_point(data = na.omit(perc_SC2_t)) + geom_point(data = na.omit(perc_FC4_t))
gross_vol_all
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\figures\\gross_vol-tdf_all_fire.png', plot = gross_vol_all, device = 'png')
```

```{r}
gross_vol_all_45 = ggplot(data = na.omit(gross_sum_t_perc_t), aes(Time, Volume, color = Fire, group = Site)) + geom_point() + geom_line() + ggtitle('Estimated Percent Volume over Time') + xlab('Time Since Debris Flow (Years)') + ylab('Percent Remaining Volume') + ylim(45,100) + scale_x_discrete(limit = c('EstInt','0', '1','2','3','4','5','6','7','8','9','10')) + theme_bw() + geom_line(data= na.omit(perc_FC5_1_t)) + geom_line(data= na.omit(perc_FC5_2_t)) + geom_line(data= na.omit(perc_FC7_t)) + geom_line(data = na.omit(perc_SC2_t)) +geom_line(data = na.omit(perc_FC4_t)) +ggtitle('Debris Flow Fan Estimated Volume over Time')+ geom_point(data = na.omit(perc_FC5_1_t)) + geom_point(data= na.omit(perc_FC5_2_t))  + geom_point(data= na.omit(perc_FC7_t)) + geom_point(data = na.omit(perc_SC2_t)) + geom_point(data = na.omit(perc_FC4_t))
gross_vol_all_45
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\figures\\gross_vol-tdf_all45_fire.png', plot = gross_vol_all_45, device = 'png')
```

```{r}
twitchell_plot = ggplot(data = na.omit(twitchell_t), aes(Time, Volume, color = Site, group = Site)) + geom_point() +  xlab('Years since Debris Flow') + ylab('Percent Remaining Volume') + geom_line()  + geom_line(data= na.omit(perc_FC5_1_t)) + geom_line(data= na.omit(perc_FC5_2_t))  + geom_line(data= na.omit(perc_FC7_t)) + geom_line(data = na.omit(perc_SC2_t)) +geom_line(data = na.omit(perc_FC4_t)) +ggtitle('Twitchell Volume')+ geom_point(data = na.omit(perc_FC5_1_t)) + geom_point(data= na.omit(perc_FC5_2_t)) + geom_point(data= na.omit(perc_FC7_t)) + geom_point(data = na.omit(perc_SC2_t)) + geom_point(data = na.omit(perc_FC4_t)) + ylim(0,100) + scale_x_discrete(limit = c('EstInt','0', '1','2','3','4','5','6','7','8','9','10')) + theme_bw()
twitchell_plot
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\figures\\twitchell_vol-tdf.png', plot = twitchell_plot, device = 'png')
```
```{r}
gross_voltdf_bh = ggplot(data = (brian_head_t), aes(Time, Volume, color = Site, group = Site)) + geom_point() +  xlab('Years since Debris Flow') + ylab('Percent Remaining Volume') + geom_line(data = na.omit(brian_head_t)) +ggtitle('Brian Head Volume') + ylim(0,100) + scale_x_discrete(limits = c('EstInt','0', '1','2','3')) + theme_bw()
gross_voltdf_bh
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\figures\\brianhead_vol-tdf.png', plot = gross_voltdf_bh, device = 'png')
```
```{r}
gross_voltdf_dr = ggplot(data = na.omit(dollar_ridge_t), aes(Time, Volume, color = Site, group = Site)) + geom_point() +  xlab('Years since Debris Flow') + ylab('Percent Remaining Volume') +  geom_line() +ggtitle('Dollar Ridge Volume')+ ylim(0,100) + scale_x_discrete(limit = c('EstInt', '0', '1', '2', '3')) + theme_bw()
gross_voltdf_dr
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\figures\\dollarridge_vol-tdf.png', plot = gross_voltdf_dr, device = 'png')
```

```{r}
gross_voltdf_pc = ggplot(data = na.omit(pole_creek_t), aes(Time, Volume, color = Site, group = Site)) + geom_point() +  xlab('Years since Debris Flow') + ylab('Percent Remaining Volume')  +  geom_line() +ggtitle('Pole Creek Volume')+ ylim(0,100) + scale_x_discrete(limit = c('EstInt', '0', '1', '2', '3')) + theme_bw()
gross_voltdf_pc
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\figures\\polecreek_vol-tdf.png', plot = gross_voltdf_pc, device = 'png')
```
```{r}
gross_voltdf_seeley = ggplot(data = na.omit(seeley_t), aes(Time, Volume, color = Site, group = Site)) + geom_point() +  xlab('Years since Debris Flow') + ylab('Percent Remaining Volume') +  geom_line() +ggtitle('Seeley Volume')+ ylim(0,100) + scale_x_discrete(limit = c('EstInt', '0', '1', '2', '3','4','5','6','7','8','9')) + theme_bw()
gross_voltdf_seeley
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\figures\\seeley_vol-tdf.png', plot = gross_voltdf_seeley, device = 'png')
```
```{r}
gross_voltdf_shingle = ggplot(data = na.omit(shingle_t), aes(Time, Volume, color = Site, group = Site)) + geom_point() +  xlab('Years since Debris Flow') + ylab('Percent Remaining Volume')  +  geom_line() +ggtitle('Shingle Volume')+ ylim(0,100)+ scale_x_discrete(limit = c('EstInt', '0', '1', '2', '3','4','5','6','7','8')) + theme_bw()
gross_voltdf_shingle
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\figures\\shingle_vol-tdf.png', plot = gross_voltdf_shingle, device = 'png')
```
```{r}
gross_voltdf_cs = ggplot(data = na.omit(clay_springs_t), aes(Time, Volume, color = Site, group = Site)) + geom_point() +  xlab('Years since Debris Flow') + ylab('Percent Remaining Volume') +  geom_line() +ggtitle('Clay Springs Volume')+ ylim(0,100) + scale_x_discrete(limit = c('EstInt', '0', '1', '2', '3', '4', '5','6','7')) + theme_bw()
gross_voltdf_cs
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\figures\\claysprings_vol-tdf.png', plot = gross_voltdf_cs, device = 'png')
```
```{r}
gross_voltdf_tm = ggplot(data = na.omit(trail_mountain_t), aes(Time, Volume, color = Site, group = Site)) + geom_point() +  xlab('Years since Debris Flow') + ylab('Percent Remaining Volume') +  geom_line() +ggtitle('Trail Mountain Volume')+ ylim(0,100) + scale_x_discrete(limit = c('EstInt', '0', '1', '2', '3','4')) + theme_bw()
gross_voltdf_tm
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\figures\\trailmountain_vol-tdf.png', plot = gross_voltdf_tm, device = 'png')
```
```{r}
vol_comp = read.csv('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\processed_summary_data\\volume_comps.csv', header = T, na.strings = ' ')
head(vol_comp)
```
```{r}
vol_reg_obs = vol_comp[,c(1:2,6)]
```

```{r}
vol_ratio = vol_reg_obs
vol_ratio$Ratio = NA
vol_ratio$Used = NA
```
```{r}
vol_ratio$Ratio = vol_ratio[,3]/vol_ratio[,2]
vol_ratio = vol_ratio[,-c(3)]
```

```{r}
vol_ratio[c(2,9,12,13,14,16,19,23), 4] = 'Used'
vol_ratio[c(1,3,4,5,6,7,8,10,11,15,17,18,20,21,22,24:29),4] = 'Not Used'
group = c('Y','N')
```

```{r}
library(ggplot2)
vol_ratio_plot = ggplot(data = vol_ratio, aes(obs_vol, Ratio, shape = Used)) + geom_point() + scale_color_manual(values = c('black','black')) + scale_shape_manual(values = c(1, 16)) + xlab('Observed Volume (m3)') + ylab('Modeled/Observed Volume') + ggtitle('2020 Modeled vs Observed Volume') + theme_bw() + labs(shape ='Sites used in this study')+ expand_limits(x=0,y=0)+ theme(legend.position = 'right') + geom_hline(yintercept = 1, linetype = 'dashed', color = 'red')
vol_ratio_plot
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\data\\figures\\VolRatio2020.png', plot = vol_ratio_plot, device = 'png')
```
```{r}
write.csv(gross_sum_t_perc, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\processed_summary_data\\R_outputs\\gross_sum_percent.csv', row.names = TRUE)
write.csv(perc_FC4_1, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Twitchell\\FC4_percent.csv', row.names = TRUE)
write.csv(perc_FC5_1, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Twitchell\\FC5_1_percent.csv', row.names = TRUE)
write.csv(perc_FC5_2, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Twitchell\\FC5_2_percent.csv', row.names = TRUE)
write.csv(perc_FC7, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Twitchell\\FC7_percent.csv')
write.csv(perc_SC2, file = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\raw_site_data\\Twitchell\\SC2_percent.csv')
```

