```{R}
folder = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\data_sheets\\processed_summary_data'
setwd(folder)
library(readxl)
gsdvol= read_excel('Catchment_Stats.xlsx', sheet = 'Vol_Summaries', na = ' ')
```
```{r}
est_vol = gsdvol[c(1,2)]
wall_vol = gsdvol[,c(1,3)]
g14 = gsdvol[,c(1,8)]
```
```{r}
est = 'imagery'
wall = 'Wall (2022)'
gart = 'Gartner (2014) 1yr'
```


```{r}
wall_vol = cbind(wall_vol, wall)
colnames(wall_vol) = c('Site','VolM', 'Source')
g14 = cbind(g14, gart)
colnames(g14) = c('Site','VolM', 'Source')
```
```{r}
est_vol = cbind(est_vol, est)
colnames(est_vol)= c('Site', 'VolM', 'Source')
```

```{r}
all = rbind(g14, wall_vol)
all = cbind(all, est_vol[2])
colnames(all) = c('Site', 'VolM', 'Source', 'EstVol')
gartnervol = cbind(g14, est_vol[2])
colnames(gartnervol) = c('Site', 'VolM', 'Source', 'EstVol')
```


```{r}
risd = gartnervol[,-c(3)]
risd$diff = NA
rows = c(1:31)
for (i in rows){
  risd[i,4] = (risd[i,2]-risd[i,3])
}
g14_out = boxplot.stats(risd$diff, coef = 1)$out
g14_outind = which(risd$diff %in% c(g14_out))
risddev = sd(na.omit(risd$diff))
```


```{r}
wallsd = wallestvol[,-c(3)]
wallsd$diff= NA
rows = c(1:31)
for (i in rows){
  wallsd[i,4] = (wallsd[i,2]-wallsd[i,3])
}
wall_out = boxplot.stats(wallsd$diff)$out
wall_outind = which(wallsd$diff %in% c(wall_out))
walldev = sd(na.omit(wallsd$diff))
```

```{r}
allsd = all[,-c(3)]
allsd$diff = NA
rows = c(1:62)
for (i in rows){
  allsd[i,4]= (allsd[i,2]- allsd[i,3])
}
```
```{r}
out = boxplot.stats(allsd$diff)$out
out_ind = which(allsd$diff %in% c(out))
all_nout = allsd[-c(out_ind),]
```
```{r}
alldev = sd(na.omit(all_nout$diff))
```
```{r}
library(ggplot2)
gartnervol_plot = ggplot(data = na.omit(gartnervol), aes(EstVol, VolM, color = Source)) + geom_point() +geom_abline(mapping = NULL, data = NULL, 1, 0) + xlim(0,15000) + ylim(0,15000) +ylab('Modeled Initial Volume (m3)') + xlab('Estimated Initial Volume from Imagery (m3)') + ggtitle('Gartner (2014) Modeled Volume') + geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = gartdev, linetype = 'dashed')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = -gartdev, linetype = 'dashed') + expand_limits(x=0,y=0) +theme_bw()
gartnervol_plot
#ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\data\\data_sheets\\figures\\gartner_vol.png', plot = gartnervol_plot, device = 'png')
```
```{r}
RIvol_plot = ggplot(data = na.omit(RIvol), aes(EstVol, VolM, color = Source)) + geom_point() + geom_abline(mapping = NULL, data = NULL, 1, 0) + xlim(0,15000) + ylim(0,15000) +ylab('Modeled Initial Volume (m3)') + xlab('Estimated Initial Volume from Imagery (m3)') + ggtitle('Gartner (2014) Modeled Volume using 15 min Recurrence Intervals') + theme_bw() + geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = risddev, linetype = 'dashed')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = -risddev, linetype = 'dashed') + labs(color ='Recurrence Interval')+ expand_limits(x=0,y=0)+ coord_cartesian(expand = FALSE)
RIvol_plot
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\data\\data_sheets\\figures\\gartner_ri_vol.png', plot = RIvol_plot, device = 'png')
```
```{r}
histgageplot = ggplot(data = na.omit(histgagevol), aes(EstVol, VolM, color = Source)) + geom_point() + geom_abline(mapping = NULL, data = NULL, 1, 0) +xlim(0,15000) + ylim(0,15000) +ylab('Modeled Initial Volume (m3)') + xlab('Estimated Initial Volume from Imagery (m3)') + ggtitle('Gartner (2014) Modeled Volume using Historical 15 min Gage Data') + theme_bw() + theme(legend.position = 'none') + geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = histgagedev, linetype = 'dashed')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = -histgagedev, linetype = 'dashed') + expand_limits(x=0,y=0)
histgageplot
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\data\\data_sheets\\figures\\gartner_obs_vol.png', plot = histgageplot, device = 'png')
```

```{r}
wallvolplot = ggplot(data = na.omit(wallestvol)) + geom_point(data = wallestvol, aes(EstVol, VolM, color = Source)) + scale_color_manual(values = c('Wall'= 'cornflowerblue')) +geom_abline(mapping = NULL, data = NULL, 1, 0) +xlim(0,15000) + ylim(0,15000) +ylab('Modeled Initial Volume (m3)') + xlab('Estimated Initial Volume from Imagery (m3)') + ggtitle('Wall (2022) Volume Model')+ theme_bw() + theme(legend.position = 'none')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = walldev, linetype = 'dashed')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = -walldev, linetype = 'dashed')+ expand_limits(x=0,y=0)
wallvolplot
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\data\\data_sheets\\figures\\wall_vol.png', plot = wallvolplot, device = 'png')
```

```{r}
allplot = ggplot(data = na.omit(all), aes(EstVol, VolM, shape= Source)) + geom_point() +scale_color_manual(values = c('black','black')) + scale_shape_manual(values = c(1, 16)) + geom_abline(mapping = NULL, data = NULL, 1, 0) + ylim(0,32000) +ylab('Modeled Initial Volume (m3)') + xlab('Estimated Initial Volume from Imagery (m3)')  + theme_bw()+ labs(color ='Volume Model')+ expand_limits(x=0,y=0) + theme(legend.position = 'none')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = -alldev, linetype = 'dashed') + geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = alldev, linetype = 'dashed')
allplot
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\debris_flow_stats\\data\\figures\\plots\\allvol.png', plot = allplot, device = 'png')
```
```{r}
lnvolwall = gsdvol[,c(1,21)]
lnvolwall$Source = 'Wall'
lnvolg14 = gsdvol[,c(1,28)]
lnvolg14$Source = 'Gartner 14'
lnvolimg = gsdvol[,c(1,29)]
lnvolimg$Source = 'Imagery'
lnvolwall = cbind(lnvolwall, lnvolimg[2])
lnvolg14 = cbind(lnvolg14, lnvolimg[2])
colnames(lnvolwall) = c('Site', 'ln_vol', 'Source', 'LnEstInt')
colnames(lnvolg14) = c('Site', 'ln_vol', 'Source', 'LnEstInt')
colnames(lnvolimg) = c('Site', 'ln_vol', 'Source', 'LnEstInt')
```

```{r}
lnvol = rbind(lnvolwall,lnvolg14)
```

```{r}
lnvolplot = ggplot(data = lnvol, aes(LnEstInt,ln_vol, color = Source)) + geom_point() +  geom_abline(mapping = NULL, data = NULL, 1, 0) +ylab('ln(Modeled Volume) (m3)') + xlab('ln(Estimated Initial Volume from Imagery) (m3)') + ggtitle('ln(Vol)') + theme_bw() +ylim(0,11) + xlim(0,11)
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\data\\data_sheets\\figures\\allvol.png', plot = lnvolplot, device = 'png')
lnvolplot
```
```{R}
folder = 'C:\\Users\\clang\\Documents\\USU\\DF_Areas\\data\\data_sheets\\processed_summary_data'
setwd(folder)
library(readxl)
gsdvol= read_excel('Catchment_Stats_gartneredits_1.xlsx', sheet = 'GSD and Vol Est', na = ' ')
```
```{r}
est_vol = gsdvol[c(1,23)]
wall_vol = gsdvol[,c(1,21)]
g14obs = gsdvol[,c(1,22)]
g14_1yr = gsdvol[,c(1,24)]
g14_2yr = gsdvol[,c(1,25)]
g14_5yr = gsdvol[,c(1,26)]
g14_10yr = gsdvol[,c(1,27)]
g14_25yr = gsdvol[,c(1,28)]
g14_50yr = gsdvol[,c(1,29)]
```
```{r}
est = 'imagery'
wall = 'Wall'
gobs = 'Historical 15min Gage'
g1 = '1 year RI'
g2 = '2 year RI'
g5 = '5 year RI'
g10 = '10 year RI'
g25 = '25 year RI'
g50 = '50 year RI'
gart = 'Recurrence Interval Estimate'
```


```{r}
wall_vol = cbind(wall_vol, wall)
colnames(wall_vol) = c('Site','VolM', 'Source')
g14obs = cbind(g14obs, gobs)
colnames(g14obs) = c('Site','VolM', 'Source')
g14_1yr = cbind(g14_1yr, g1)
colnames(g14_1yr) = c('Site', 'VolM', 'Source')
g14_2yr = cbind(g14_2yr, g2)
colnames(g14_2yr) = c('Site','VolM', 'Source')
g14_5yr = cbind(g14_5yr, g5)
colnames(g14_5yr) = c('Site','VolM', 'Source')
g14_10yr = cbind(g14_10yr, g10)
colnames(g14_10yr) = c('Site','VolM', 'Source')
g14_25yr = cbind(g14_25yr, g25)
colnames(g14_25yr) = c('Site','VolM', 'Source')
g14_50yr = cbind(g14_50yr, g50)
colnames(g14_50yr) = c('Site','VolM', 'Source')
```
```{r}
est_vol = cbind(est_vol, est)
colnames(est_vol)= c('Site', 'VolM', 'Source')
g14_1yrg = cbind(g14_1yr[1:2], gart)
colnames(g14_1yrg) = c('Site', 'VolM', 'Source')
g14_2yrg = cbind(g14_2yr[1:2], gart)
colnames(g14_2yrg) = c('Site','VolM', 'Source')
g14_5yrg = cbind(g14_5yr[1:2], gart)
colnames(g14_5yrg) = c('Site','VolM', 'Source')
g14_10yrg = cbind(g14_10yr[1:2], gart)
colnames(g14_10yrg) = c('Site','VolM', 'Source')
g14_25yrg = cbind(g14_25yr[1:2], gart)
colnames(g14_25yrg) = c('Site','VolM', 'Source')
g14_50yrg = cbind(g14_50yr[1:2], gart)
colnames(g14_50yrg) = c('Site','VolM', 'Source')
```

```{r}
all1 = rbind(g14_1yrg, g14_2yrg, g14_5yrg,g14_10yrg,g14_25yrg,g14_50yrg,g14obs,wall_vol)
all1 = cbind(all1, est_vol[2])
colnames(all1) = c('Site', 'VolM', 'Source', 'EstVol')
RIvol1= rbind(g14_1yr, g14_2yr,g14_5yr,g14_10yr,g14_25yr,g14_50yr)
gartnervol1 = rbind(RIvol1, g14obs)
gartnervol1 = cbind(gartnervol1, est_vol[2])
```
```{r}
RIvol1= cbind(RIvol1, est_vol[2])
colnames(gartnervol1) = c('Site', 'VolM', 'Source', 'EstVol')
colnames(RIvol1) = c('Site', 'VolM', 'Source', 'EstVol')
histgagevol = cbind(g14obs,est_vol[2])
colnames(histgagevol) = c('Site', 'VolM', 'Source', 'EstVol')
wallestvol = cbind(wall_vol, est_vol[2])
colnames(wallestvol) = c('Site', 'VolM', 'Source', 'EstVol')
```

```{r}
histgagesd = histgagevol[,-c(3)]
histgagesd$diff = NA
rows = c(1:33)
for (i in rows){
  histgagesd[i,4] = (histgagesd[i,2]-histgagesd[i,3])
}
histgagedev = sd(na.omit(histgagesd$diff))
```

```{r}
risd1 = RIvol1[,-c(3)]
risd1$diff = NA
rows = c(1:330)
for (i in rows){
  risd1[i,4] = (risd1[i,2]-risd1[i,3])
}
risddev1 = sd(na.omit(risd1$diff))
```

```{r}
gartsd1 = gartnervol1[,-c(3)]
gartsd1$diff = NA
rows = c(1:363)
for (i in rows){
  gartsd1[i,4] = (gartsd1[i,2]-gartsd1[i,3])
}
gartdev1 = sd(na.omit(gartsd1$diff))
gartvar = var(na.omit(gartsd1$diff))
```
```{r}
wallsd = wallestvol[,-c(3)]
wallsd$diff= NA
rows = c(1:33)
for (i in rows){
  wallsd[i,4] = (wallsd[i,2]-wallsd[i,3])
}
walldev = sd(na.omit(wallsd$diff))
```

```{r}
allsd1 = all1[,-c(3)]
allsd1$diff = NA
rows = c(1:396)
for (i in rows){
  allsd1[i,4]= (allsd1[i,2]- allsd1[i,3])
}
alldev1 = sd(na.omit(allsd1$diff))
```
```{r}
library(ggplot2)
gartnervol_plot1 = ggplot(data = na.omit(gartnervol1), aes(EstVol, VolM, color = Source)) + geom_point() +geom_abline(mapping = NULL, data = NULL, 1, 0) + xlim(0,15500) + ylim(0,15500) +ylab('Modeled Initial Volume (m3)') + xlab('Estimated Initial Volume from Imagery (m3)') + ggtitle('Gartner (2014) Modeled Volume') + geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = gartdev1, linetype = 'dashed')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = -gartdev1, linetype = 'dashed') + expand_limits(x=0,y=0) +theme_bw() + scale_color_manual(name = '15-Minute Rainfall Intensity Source', breaks = c('1 year RI', '5 year RI', '10 year RI', '50 year RI', 'Historical Rain Gage'), values = c('1 year RI' = 'coral2', '5 year RI' = 'cyan', '10 year RI' = 'purple','Historical Rain Gage' = 'black')) + coord_cartesian(expand = FALSE)
gartnervol_plot1
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\data\\data_sheets\\figures\\gartner_vol_1.png', plot = gartnervol_plot1, device = 'png')
```
```{r}
RIvol_plot1 = ggplot(data = na.omit(RIvol1), aes(EstVol, VolM, color = Source)) + geom_point() + geom_abline(mapping = NULL, data = NULL, 1, 0) + xlim(0,15500) + ylim(0,15500) +ylab('Modeled Initial Volume (m3)') + xlab('Estimated Initial Volume from Imagery (m3)') + ggtitle('Gartner (2014) Modeled Volume using 15 min Recurrence Intervals') + theme_bw() + geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = risddev1, linetype = 'dashed')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = -risddev1, linetype = 'dashed') + labs(color = 'Recurrence Interval') + expand_limits(x=0,y=0)+ coord_cartesian(expand = FALSE)
RIvol_plot1
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\data\\data_sheets\\figures\\gartner_ri_vol_1.png', plot = RIvol_plot1, device = 'png')
```
```{r}
histgageplot = ggplot(data = na.omit(histgagevol), aes(EstVol, VolM, color = Source)) + geom_point() + geom_abline(mapping = NULL, data = NULL, 1, 0) +xlim(0,15000) + ylim(0,15000) +ylab('Modeled Initial Volume (m3)') + xlab('Estimated Initial Volume from Imagery (m3)') + ggtitle('Gartner (2014) Modeled Volume using Historical 15 min Gage Data') + theme_bw() + theme(legend.position = 'none') + geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = histgagedev, linetype = 'dashed')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = -histgagedev, linetype = 'dashed') + expand_limits(x=0,y=0)
histgageplot
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\data\\data_sheets\\figures\\gartner_obs_vol.png', plot = histgageplot, device = 'png')
```

```{r}
wallvolplot = ggplot(data = na.omit(wallestvol)) + geom_point(data = wallestvol, aes(EstVol, VolM, color = Source)) + scale_color_manual(values = c('Wall'= 'cornflowerblue')) +geom_abline(mapping = NULL, data = NULL, 1, 0) +xlim(0,15000) + ylim(0,15000) +ylab('Modeled Initial Volume (m3)') + xlab('Estimated Initial Volume from Imagery (m3)') + ggtitle('Wall (2022) Volume Model')+ theme_bw() + theme(legend.position = 'none')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = walldev, linetype = 'dashed')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = -walldev, linetype = 'dashed')+ expand_limits(x=0,y=0)
wallvolplot
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\data\\data_sheets\\figures\\wall_vol.png', plot = wallvolplot, device = 'png')
```

```{r}
allplot1 = ggplot(data = na.omit(all1), aes(EstVol, VolM, color = Source)) + geom_point() + geom_abline(mapping = NULL, data = NULL, 1, 0) + ylim(0,15000) +ylab('Modeled Initial Volume (m3)') + xlab('Estimated Initial Volume from Imagery (m3)') + ggtitle('Gartner (2014) and Wall (2022) Volume Models') + theme_bw()+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = alldev1, linetype = 'dashed')+ geom_abline(mapping = NULL, data = NULL, slope = 1, intercept = -alldev1, linetype = 'dashed')+ labs(color ='Volume Model')+ expand_limits(x=0,y=0) 
allplot1
ggsave('C:\\Users\\clang\\Documents\\USU\\DF_Areas\\data\\data_sheets\\figures\\allvol_1.png', plot = allplot1, device = 'png')
```